### ISSUE TITLE
Incorrect DbWeight for update_job_assignments pallet call method.

### ISSUE THREAD

**Issue by web3online** [Acurast/acurast-core#12]
### Method `update_job_assignments` contains incorrect weight:

`#[pallet::weight(10_000 + T::DbWeight::get().reads_writes(2, 1))]`

There are iteration through the updates vector:
The input vec should be used for specifying the weight 
So 2 reads and 1 set db per each element for updates Vector.

```
pub fn update_job_assignments(
    origin: OriginFor<T>,
    updates: Vec<JobAssignmentUpdate<T::AccountId>>,
) -> DispatchResultWithPostInfo {
    let who = ensure_signed(origin)?;
    if !T::JobAssignmentUpdateBarrier::can_update_assigned_jobs(&who, &updates) {
        return Err(Error::<T>::JobAssignmentUpdateNotAllowed)?;
    }
    for update in &updates {
        let job_registration =
            <StoredJobRegistration<T>>::get(&update.job_id.0, &update.job_id.1)
                .ok_or(Error::<T>::JobRegistrationNotFound)?;

        ensure_source_allowed::<T>(&update.assignee, &job_registration)?;

        let mut assignments =
            <StoredJobAssignment<T>>::get(&update.assignee).unwrap_or_default();
        if !assignments.contains(&update.job_id) {
            assignments.push(update.job_id.clone());
        }
        <StoredJobAssignment<T>>::set(&update.assignee, Some(assignments));
    }
    Self::deposit_event(Event::JobAssignmentUpdate(who, updates));
    Ok(().into())
}
```

### There is additional db read inside `ensure_source_allowed` method:

```
let attestation =  <StoredAttestation<T>>::get(source).ok_or(Error::<T>::FulfillSourceNotVerified)?;
```

**Comment by RomarQ** [comment]
Thank you for the remark :+1:

There is currently a task going on to benchmark and update the weights of all extrinsic calls.

The `update_job_assignments` is supposed to be temporary and will be removed in the future.

**Comment by RomarQ** [comment]
The benchmarks and the respective call weights were added to [acurast pallet](https://github.com/Acurast/acurast-core/blob/20d56bc9fa92beb6122ada6f11a82e0f31d3b451/pallets/acurast/src/weights.rs#L64).

Closing the issue.

**Comment by web3online** [comment]
Amazing!
